### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by georgiosd** [markedup-mobi/hircine#14]

**Comment by Aaronontheweb** [comment]
@georgiosd this project is no longer actively maintained by MarkedUp. Our company stopped using RavenDB due to immense scalability problems with it: http://blog.markedup.com/2013/02/cassandra-hive-and-hadoop-how-we-picked-our-analytics-stack/

And for reasons that baffle me, the RavenDB 1.0 client is not forward-compatible with RavenDB 2.0 servers (last time I checked it, which was just after the stable release of 2.0) nor is the RavenDB 2.0 client back-ward compatible with RavenDB 1.0 servers. Given that, it is unlikely that we'd be able to support Raven1.0 and Raven2.0 users simultaneously without a major redesign of Hircine.
